In [2]:
import numpy as np
#from numpy import array as ar

In [3]:
a_list=[10,11,12,13]
print(type(a_list))

<class 'list'>


In [4]:
len(a_list)

4

In [6]:
a_list[len(a_list)-1]

13

In [7]:
array_1=np.array(a_list)

In [8]:
array_1

array([10, 11, 12, 13])

In [9]:
type(array_1)

numpy.ndarray

In [10]:
array_1[0]

10

In [11]:
array_1[-1]

13

In [21]:
#len(array_1)
#array_1.shape
#array_1.size
#array_1.dtype
#array_1.ndim

In [19]:
#np.mean(array_1)
#np.std(array_1)

In [30]:
array_2d=np.array([[11.0,12,13],[14,15,16],[17,18,19],[2,3,4]])

In [31]:
array_2d

array([[11., 12., 13.],
       [14., 15., 16.],
       [17., 18., 19.],
       [ 2.,  3.,  4.]])

In [34]:
#len(array_2d)
#array_2d.shape
#array_2d.size
#array_2d.dtype
#array_2d.ndim

2

In [36]:
array_2d

array([[11., 12., 13.],
       [14., 15., 16.],
       [17., 18., 19.],
       [ 2.,  3.,  4.]])

In [40]:
#sum(array_2d)
array_2d.sum(axis=1)

array([36., 45., 54.,  9.])

In [45]:
list(range(2,10,2))

[2, 4, 6, 8]

In [49]:
array_2d[:]

array([[11., 12., 13.],
       [14., 15., 16.],
       [17., 18., 19.],
       [ 2.,  3.,  4.]])

In [62]:
#array_2d[0,:]
#array_2d[:,1]
#array_2d[2:4,1:]
#array_2d[0:4:3,0:3:2]
#array_2d[::-1]